{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "213398d0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Scraping Page 1\n",
      "Scraping Page 2\n",
      "Scraping Page 3\n",
      "Scraping Page 4\n",
      "Scraping Page 5\n",
      "Scraping Page 6\n",
      "Scraping Page 7\n",
      "Scraping Page 8\n",
      "Scraping Page 9\n",
      "Scraping Page 10\n",
      "\n",
      "Done\n",
      "Total Products: 370\n",
      "CSV Saved: school_backpacks.csv\n"
     ]
    }
   ],
   "source": [
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.service import Service\n",
    "from webdriver_manager.chrome import ChromeDriverManager\n",
    "from bs4 import BeautifulSoup\n",
    "import pandas as pd\n",
    "import time\n",
    "import re\n",
    "\n",
    "driver = webdriver.Chrome(\n",
    "    service=Service(ChromeDriverManager().install())\n",
    ")\n",
    "\n",
    "all_products = []\n",
    "\n",
    "for page in range(1, 11):\n",
    "\n",
    "    print(f\"Scraping Page {page}\")\n",
    "\n",
    "    url = f\"https://mbgtoys.com/en/group-681-School-backpacks?page={page}\"\n",
    "\n",
    "    driver.get(url)\n",
    "\n",
    "    time.sleep(5)\n",
    "\n",
    "    soup = BeautifulSoup(driver.page_source, \"html.parser\")\n",
    "\n",
    "    products_div = soup.find(class_=\"products\")\n",
    "\n",
    "    if not products_div:\n",
    "        continue\n",
    "\n",
    "    text = products_div.get_text(\"\\n\", strip=True)\n",
    "\n",
    "    lines = [x.strip() for x in text.split(\"\\n\") if x.strip()]\n",
    "\n",
    "    i = 0\n",
    "\n",
    "    while i < len(lines):\n",
    "\n",
    "        if re.match(r'^\\d+\\.\\d+\\s*€', lines[i]):\n",
    "\n",
    "            price = lines[i]\n",
    "\n",
    "            availability = \"\"\n",
    "\n",
    "            if i + 2 < len(lines):\n",
    "                availability = lines[i + 2]\n",
    "\n",
    "            product_name = \"\"\n",
    "\n",
    "            if i + 4 < len(lines):\n",
    "                product_name = lines[i + 4]\n",
    "\n",
    "            all_products.append({\n",
    "                \"Product Name\": product_name,\n",
    "                \"Price\": price,\n",
    "                \"Availability\": availability\n",
    "            })\n",
    "\n",
    "            i += 4\n",
    "\n",
    "        i += 1\n",
    "\n",
    "driver.quit()\n",
    "\n",
    "df = pd.DataFrame(all_products)\n",
    "\n",
    "df = df.drop_duplicates()\n",
    "\n",
    "df.to_csv(\n",
    "    \"school_backpacks.csv\",\n",
    "    index=False,\n",
    "    encoding=\"utf-8-sig\"\n",
    ")\n",
    "\n",
    "print(\"\\nDone\")\n",
    "print(\"Total Products:\", len(df))\n",
    "print(\"CSV Saved: school_backpacks.csv\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
